CREATE DATABASE IF NOT EXISTS offline_auth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE offline_auth;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  password_hash CHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
