/** @type {import(tailwindcss).Config} */
export default {
  content: [
    ./index.html,
    ./*.{js,ts,jsx,tsx},
    ./pages/**/*.{js,ts,jsx,tsx},
    ./components/**/*.{js,ts,jsx,tsx}
  ],
  theme: {
    extend: {
      colors: {
        primary: #4359F5,
        primary-dark: #233cdc,
        primary-light: #dfe0ff,
        primary-dim: #bcc2ff,
        surface: #f8f9ff,
        surface-low: #eff4ff,
        surface-container: #e5eeff,
        surface-high: #dce9ff,
        surface-highest: #d3e4fe,
        background: #F1F5F9,
        on-surface: #0b1c30,
        on-surface-variant: #444655,
        on-primary: #ffffff,
        secondary: #5c5f61,
        secondary-container: #e0e3e5,
        outline: #757687,
        outline-variant: #E2E8F0,
        inverse-surface: #213145,
        tertiary: #006040,
        tertiary-container: #007b54,
        success: #10B981,
        success-bg: #D1FAE5,
        success-text: #065F46,
        warning: #F59E0B,
        warning-bg: #FEF3C7,
        warning-text: #92400E,
        danger: #EF4444,
        danger-bg: #FEE2E2,
        danger-text: #991B1B,
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', sans-serif],
      },
      fontSize: {
        2xs: [11px, { lineHeight: 14px }],
        xs: [12px, { lineHeight: 16px }],
        sm: [13px, { lineHeight: 18px }],
        base: [14px, { lineHeight: 20px }],
        md: [16px, { lineHeight: 24px }],
        lg: [18px, { lineHeight: 26px }],
        xl: [20px, { lineHeight: 28px }],
        2xl: [24px, { lineHeight: 32px }],
        3xl: [30px, { lineHeight: 38px }],
      },
      borderRadius: {
        sm: 0.25rem,
        DEFAULT: 0.5rem,
        md: 0.75rem,
        lg: 1rem,
        xl: 1.5rem,
        full: 9999px,
      },
      boxShadow: {
        card: 0px 4px 12px rgba(0,0,0,0.04), 0px 0px 0px 1px #E2E8F0,
        card-hover: 0px 8px 20px rgba(0,0,0,0.07), 0px 0px 0px 1px #C7D2FE,
        modal: 0px 20px 60px rgba(0,0,0,0.15),
      },
    },
  },
  plugins: [],
}
